STUID = 181240035
STUNAME = 刘春旭
NAME := $(shell basename $(PWD))#给NAME变量赋值，basename表示路径最后的部分
                                #e.g. input>>"basename a/b/c/d"    output<<"d"
export TASK := Lab1
all: $(NAME)-64 

include ../Makefile
include ../Makefile.lab
